[build]
  command = "echo 'No build command required for PHP'"
  publish = "/public"  # Adjust this to your public directory if different
  functions = "netlify/functions"  # For serverless functions if needed

[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"

# Redirects all requests to index.php for routing
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:;"

# CORS headers for API if needed
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
