[build]
  builder = "nixpacks"
  buildCommand = "docker build -t ujem ."
  runCommand = "/docker-entrypoint.sh"

[deploy]
  autoRollback = true
  healthcheckPath = "/"
  healthcheckTimeout = 30
  startTimeout = "300s"
  restartPolicy = "on-failure"
  restartDelay = "5s"
  maxRestarts = 5

[environments]
  [environments.production]
  # Application Settings
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_KEY = "base64:your_application_key_here"  # Generate with: `php -r "echo 'base64:'.base64_encode(random_bytes(32));"`
  
  # Database Settings
  DB_CONNECTION = "mysql"
  DB_HOST = "yamanote.proxy.rlwy.net"
  DB_PORT = "58372"
  DB_DATABASE = "railway"
  DB_USERNAME = "root"
  DB_PASSWORD = "lHrCOmGSvbbiTSntPYLwjlWMuthCRxNu"
  
  # SSL Configuration
  DB_SSL_CA = "/var/www/html/includes/cacert.pem"
  DB_SSL_VERIFY = "true"
  
  # Session Configuration
  SESSION_DRIVER = "file"
  SESSION_LIFETIME = "120"
  
  # Application URL (will be set by Railway)
  APP_URL = "https://ujem-web-production-3421.up.railway.app"
  
  # Port configuration (Railway will provide this)
  PORT = "8080"  # Will be overridden by Railway
  
  # Logging
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "error"

[services.web]
  startCommand = "/docker-entrypoint.sh"
  httpPort = 8080
  internalPort = 8080
  startTimeout = 300
  restartPolicy = "on-failure"
  restartDelay = "5s"
  maxRestarts = 5

# Configure persistent storage
[volumes]
  [volumes.uploads]
  mountPath = "/var/www/html/uploads"
  size = "1GB"
  
  [volumes.assets]
  mountPath = "/var/www/html/assets"
  size = "1GB"

[variables]
# These will be automatically provided by Railway when provisioned
# DATABASE_URL = "mysql://user:pass@host:port/dbname"
# DB_HOST is not needed when using DATABASE_URL
