[build]
builder = "docker"

[environments]
  [environments.production]
    [environments.production.variables]
      DB_HOST = {type = "string", required = true}
      DB_NAME = {type = "string", required = true}  
      DB_USER = {type = "string", required = true}
      DB_PASSWORD = {type = "secret", required = true}
